stages:
- build
- publish

image: $IMAGE_REPOSITORY/library/python:3.10-alpine

.env_before_script: &env_before_script
  before_script:
    - pip install -U pip
    - pip install 'twine>=4.0.1'
    - export BUILD_VERSION=$(echo ${CI_COMMIT_TAG:-v0.0.1} | tr -d v)

build_universal:
  stage: build
  <<: *env_before_script
  script:
  - python3 setup.py bdist_wheel --universal
  artifacts:
    paths:
    - dist
  only:
  - tags

publish_universal:
  stage: publish
  <<: *env_before_script
  script:
  - twine upload --disable-progress-bar dist/*
  only:
  - tags

